MB.Presentation.RazorPage/Areas/Administrator/Pages/ArticleCategoryManagement/ArticleCategoryCreate.cshtml.cs
using MB.Application.Contracts.ArticleCategory;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MB.Presentation.RazorPage.Areas.Administrator.Pages.ArticleCategoryManagement
{
    public class ArticleCategoryCreateModel : PageModel
    {
        

        private readonly IArticleCategoryApplication _articleCategoryApplication;

        public ArticleCategoryCreateModel(IArticleCategoryApplication articleCategoryApplication)
        {
            _articleCategoryApplication = articleCategoryApplication;
        }

        public void OnGet()
        {
            
        }

        public IActionResult OnPost(CreateArticleCategoryModel model)
        {
            _articleCategoryApplication.Create(model);
            return RedirectToPage("./ArticleCategoryList");
        }
    }
}

MB.Presentation.RazorPage/Areas/Administrator/Pages/ArticleCategoryManagement/ArticleCategoryEdit.cshtml.cs
using MB.Application.Contracts.ArticleCategory;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MB.Presentation.RazorPage.Areas.Administrator.Pages.ArticleCategoryManagement
{
    public class ArticleCategoryEditModel : PageModel
    {
        [BindProperty] public EditArticleCategoryModel ArticleCategory { get; set; }
        private readonly IArticleCategoryApplication _articleCategoryApplication;

        public ArticleCategoryEditModel(IArticleCategoryApplication articleCategoryApplication)
        {
            _articleCategoryApplication = articleCategoryApplication;
        }

        public void OnGet(int id)
        {
           ArticleCategory= _articleCategoryApplication.GetById(id);
        }

        public IActionResult OnPost()
        {
            _articleCategoryApplication.Edit(ArticleCategory);
            return RedirectToPage("./ArticleCategoryList");
        }
    }
}

MB.Presentation.RazorPage/Areas/Administrator/Pages/ArticleCategoryManagement/ArticleCategoryList.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using MB.Application.Contracts.ArticleCategory;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MB.Presentation.RazorPage.Areas.Administrator.Pages.ArticleCategoryManagement
{
    public class ArticleCategoryListModel : PageModel
    {

        public List<ArticleCategoryViewModel> ArticleCategories { get; set; }
        private readonly IArticleCategoryApplication _articleCategoryApplication;

        public ArticleCategoryListModel(IArticleCategoryApplication articleCategoryApplication)
        {
            _articleCategoryApplication = articleCategoryApplication;
        }

        public void OnGet()
        {
            ArticleCategories = _articleCategoryApplication.GetAll().ToList();
        }

        public IActionResult OnPostActivate(int id)
        {
            _articleCategoryApplication.Active(id);
            return RedirectToPage("./ArticleCategoryList");
        }
        
        public IActionResult OnPostDeActive(int id)
        {
            _articleCategoryApplication.DeActive(id);
            return RedirectToPage("./ArticleCategoryList");
        }
    }
}

MB.Presentation.RazorPage/Areas/Administrator/Pages/ArticleCategoryManagement/ArticleCategoryCreate.cshtml
@page
@model MB.Presentation.RazorPage.Areas.Administrator.Pages.ArticleCategoryManagement.ArticleCategoryCreateModel
@{
}
<div class="card">
    <div class="card-header">
        <h2>Create New Article Category</h2>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-12">
                <form method="post">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="col-md-6 col-sm-12">
                        <div class="form-group">
                            <label for="Title" class="control-label">Title:</label>
                            <input name="Name" id="Title" class="form-control" />
                        </div>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-success" />
                        <a class="btn btn-dark" asp-page="./ArticleCategoryList" asp-area="Administrator">Back to list</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

MB.Presentation.RazorPage/Areas/Administrator/Pages/ArticleCategoryManagement/ArticleCategoryEdit.cshtml
@page "{id:int}"
@model MB.Presentation.RazorPage.Areas.Administrator.Pages.ArticleCategoryManagement.ArticleCategoryEditModel
@{
}
@*<form method="post">
    <label asp-for="ArticleCategory.Name"></label>
    <input asp-for="ArticleCategory.Name"/>
    <input type="hidden" asp-for="ArticleCategory.Id" />
    <input type="submit"/>
</form>*@



<div class="card">
    <div class="card-header">
        <h2>Edit Article Category: @Model.ArticleCategory.Name</h2>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-12">
                <form method="post">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="ArticleCategory.Id" />
                    <div class="col-md-6 col-sm-12">
                        <div class="form-group">
                            <label asp-for="ArticleCategory.Name" class="control-label">Title:</label>
                            <input asp-for="ArticleCategory.Name" class="form-control" />
                        </div>
                    </div>
                    <div class="form-group">
                        <input type="submit" value="Edit" class="btn btn-warning" />
                        <a class="btn btn-dark" asp-page="./ArticleCategoryList" asp-area="Administrator">Back to list</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

MB.Presentation.RazorPage/Areas/Administrator/Pages/ArticleCategoryManagement/ArticleCategoryList.cshtml
@page
@model MB.Presentation.RazorPage.Areas.Administrator.Pages.ArticleCategoryManagement.ArticleCategoryListModel
@{
}


<div class="card">
    <div class="card-header">
        <h3 class="float-left">Article Category List</h3>
        <div class="float-right">
            <a class="btn btn-success" asp-page="./ArticleCategoryCreate" asp-area="Administrator">Add New</a>
        </div>
    </div>
    <div class="card-body">
        <table class="table">
            <thead>
            <tr>
                <th>Id</th>
                <th>Title</th>
                <th>Status</th>
                <th>CreationDate</th>
                <th>Operations</th>
            </tr>
            </thead>
            <tbody>
                @foreach (var articleCategory in Model.ArticleCategories)
                {
                    <tr>
                        <td>@articleCategory.Id</td>
                        <td>@articleCategory.Title</td>
                        <td>
                            @if (articleCategory.IsDeleted)
                            {
                                <i class="fa fa-close fa-2x text-danger"></i>
                            }
                            else
                            {
                                <i class="fa fa-check fa-2x text-success"></i>
                            }
                        </td>
                        <td>@articleCategory.CreationDate</td>
                        <td>
                            <a class="btn btn-warning float-left mr-3" asp-page="./ArticleCategoryEdit" asp-route-id="@articleCategory.Id">Rename</a>
                            @if (articleCategory.IsDeleted)
                            {
                                <form method="post" asp-page-handler="Activate" class="float-left">
                                    <button class="btn btn-success">Activate</button>
                                    <input type="hidden" name="id" value="@articleCategory.Id" />
                                </form>
                            }
                            else
                            {
                                <form method="post" asp-page-handler="DeActive" class="float-left">
                                    <button class="btn btn-danger">Remove</button>
                                    <input type="hidden" name="id" value="@articleCategory.Id" />
                                </form>
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>