MB.Presentation.RazorPage/Areas/Administrator/Pages/ArticleManagement/ArticleCreate.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using MB.Application.Contracts.Article;
using MB.Application.Contracts.ArticleCategory;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace MB.Presentation.RazorPage.Areas.Administrator.Pages.ArticleManagement
{
    public class ArticleCreateModel : PageModel
    {


        private readonly IArticleCategoryApplication _articleCategoryApplication;
        private readonly IArticleApplication _articleApplication;

        public ArticleCreateModel(IArticleApplication articleApplication, IArticleCategoryApplication articleCategoryApplication)
        {
            _articleApplication = articleApplication;
            _articleCategoryApplication = articleCategoryApplication;
        }

        public List<SelectListItem> ArticleCategoriesItem { get; set; }
        public void OnGet()
        {
            ArticleCategoriesItem = _articleCategoryApplication.GetAll()
                .Select(x => new SelectListItem(x.Title, x.Id.ToString())).ToList();
        }

        public IActionResult OnPost(CreateArticleModel model)
        {
            _articleApplication.Create(model);
            return RedirectToPage("./ArticleList");
        }
    }
}

MB.Presentation.RazorPage/Areas/Administrator/Pages/ArticleManagement/ArticleEdit.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using MB.Application.Contracts.Article;
using MB.Application.Contracts.ArticleCategory;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace MB.Presentation.RazorPage.Areas.Administrator.Pages.ArticleManagement
{
    public class ArticleEditModel : PageModel
    {
        [BindProperty] public EditArticleModel Article { get; set; }
        private readonly IArticleApplication _articleApplication;
        private readonly IArticleCategoryApplication _articleCategoryApplication;
        public List<SelectListItem> ArticleCategories { get; set; }

        public ArticleEditModel(IArticleApplication articleApplication, IArticleCategoryApplication articleCategoryApplication)
        {
            _articleApplication = articleApplication;
            _articleCategoryApplication = articleCategoryApplication;
        }

        public void OnGet(long id)
        {
           Article= _articleApplication.GetById(id);
           ArticleCategories = _articleCategoryApplication.GetAll()
               .Select(x => new SelectListItem(x.Title, x.Id.ToString())).ToList();

        }

        public IActionResult OnPost()
        {
            _articleApplication.Edit(Article);

            return RedirectToPage("./ArticleList");
        }

    }
}

MB.Presentation.RazorPage/Areas/Administrator/Pages/ArticleManagement/ArticleList.cshtml.cs
 using System.Collections.Generic;
using MB.Application.Contracts.Article;
using MB.Domain.ArticleAgg;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MB.Presentation.RazorPage.Areas.Administrator.Pages.ArticleManagement
{
    public class ArticleListModel : PageModel
    {
        public List<ArticleViewModel> Articles { get; set; }

        private readonly IArticleApplication _articleApplication;

        public ArticleListModel(IArticleApplication articleApplication)
        {
            _articleApplication = articleApplication;
        }

        public void OnGet()
        {
            Articles = _articleApplication.GetAll();
        }

        public RedirectToPageResult OnPostRemove(long id)
        {
            _articleApplication.Remove(id);
           return RedirectToPage("./ArticleList");

        }

        public RedirectToPageResult OnPostRestore(long id)
        {
            _articleApplication.Restore(id);
            return RedirectToPage("./ArticleList");
        }
    }
}

MB.Presentation.RazorPage/Areas/Administrator/Pages/ArticleManagement/ArticleCreate.cshtml
@page
@model MB.Presentation.RazorPage.Areas.Administrator.Pages.ArticleManagement.ArticleCreateModel
@{
}

<div class="card">
    <div class="card-header">
        <h2>Create New Article</h2>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-12">
                <form method="post">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="col-md-6 col-sm-12">
                        <div class="form-group">
                            <label for="Title" class="control-label">Title:</label>
                            <input name="Title" id="Title" class="form-control"/>
                        </div>
                    </div>

                    <div class="col-md-6 col-sm-12">
                        <div class="form-group">
                            <label for="ShortDescription" class="control-label">ShortDescription:</label>
                            <textarea name="ShortDescription" id="ShortDescription" class="form-control" rows="3"></textarea>
                        </div>
                    </div>

                    <div class="col-md-6 col-sm-12">
                        <div class="form-group">
                            <label for="Image" class="control-label">Image:</label>
                            <input name="Image" id="Image" class="form-control"/>
                        </div>
                    </div>

                    <div class="col-md-6 col-sm-12">
                        <div class="form-group">
                            <label for="Content" class="control-label">Content:</label>
                            <textarea name="Content" id="Content" class="form-control" rows="5"></textarea>
                        </div>
                    </div>

                    <div class="col-md-6 col-sm-12">
                        <div class="form-group">
                            <label for="CategoryId" class="control-label">Article Category:</label>
                            <select asp-items="Model.ArticleCategoriesItem"  name="CategoryId" id="CategoryId" class="form-control">
                                <option value="0">Select Article Category</option>
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <input type="submit" value="Create" class="btn btn-success"/>
                        <a class="btn btn-dark" asp-page="./List" asp-area="Administrator">Back to list</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

MB.Presentation.RazorPage/Areas/Administrator/Pages/ArticleManagement/ArticleEdit.cshtml
@page "{id:long}"
@model MB.Presentation.RazorPage.Areas.Administrator.Pages.ArticleManagement.ArticleEditModel
@{
}
<div class="card">
    <div class="card-header">
        <h2>Edit Article : @Model.Article.Title</h2>
    </div>
    <div class="card-body">
        <div class="row">
            <div class="col-md-12">
                <form method="post">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="Article.Id"/>
                    <div class="col-md-6 col-sm-12">
                        <div class="form-group">
                            <label asp-for="Article.Title" class="control-label">Title:</label>
                            <input asp-for="Article.Title" class="form-control"/>
                        </div>
                    </div>

                    <div class="col-md-6 col-sm-12">
                        <div class="form-group">
                            <label asp-for="Article.ShortDescription" class="control-label">ShortDescription:</label>
                            <textarea asp-for="Article.ShortDescription" class="form-control" rows="3"></textarea>
                        </div>
                    </div>

                    <div class="col-md-6 col-sm-12">
                        <div class="form-group">
                            <label asp-for="Article.Image" class="control-label">Image:</label>
                            <input asp-for="Article.Image" class="form-control"/>
                        </div>
                    </div>


                    <div class="col-md-6 col-sm-12">
                        <div class="form-group">
                            <label asp-for="Article.Content" class="control-label">Content:</label>
                            <textarea asp-for="Article.Content" class="form-control" rows="5"></textarea>
                        </div>
                    </div>

                    <div class="col-md-6 col-sm-12">
                        <div class="form-group">
                            <label asp-for="Article.CategoryId" class="control-label">Article Category:</label>
                            <select asp-for="Article.CategoryId" asp-items="Model.ArticleCategories" class="form-control">
                                <option value="0">Select Article Category</option>
                            </select>
                        </div>
                    </div>

                    <div class="form-group">
                        <input type="submit" value="Edit" class="btn btn-warning"/>
                        <a class="btn btn-dark" asp-page="./ArticleList" asp-area="Administrator">Back to list</a>
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>

MB.Presentation.RazorPage/Areas/Administrator/Pages/ArticleManagement/ArticleList.cshtml
@page
@model MB.Presentation.RazorPage.Areas.Administrator.Pages.ArticleManagement.ArticleListModel
@{
}

    <div class="card">
        <div class="card-header">
            <h3 class="float-left">Article List</h3>
            <div class="float-right">
                <a class="btn btn-success" asp-page="./ArticleCreate" asp-area="Administrator">Add New</a>
            </div>
        </div>
        <div class="card-body">
            <table class="table">
                <thead>
                    <tr>
                        <th>Id</th>
                        <th>Title</th>
                        <th>Article Category</th>
                        <th>Status</th>
                        <th>CreationDate</th>
                        <th>Operations</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var article in Model.Articles)
                    {
                        <tr>
                            <td>@article.Id</td>
                            <td>@article.Title</td>
                            <td>@article.ArticleCategory</td>
                            <td>
                                @if (article.IsDeleted)
                                {
                                    <i class="fa fa-close fa-2x text-danger"></i>
                                }
                                else
                                {
                                    <i class="fa fa-check fa-2x text-success"></i>
                                }
                            </td>
                            <td>@article.CreationDate</td>
                            <td>
                                <a class="btn btn-warning float-left mr-3" asp-page="./ArticleEdit" asp-route-id="@article.Id">Edit</a>
                                @if (article.IsDeleted)
                                {
                                    <form method="post" asp-page-handler="Restore" class="float-left">
                                        <button class="btn btn-success">Activate</button>
                                        <input type="hidden" name="id" value="@article.Id" />
                                    </form>
                                }
                                else
                                {
                                    <form method="post" asp-page-handler="Remove" class="float-left">
                                        <button class="btn btn-danger">Remove</button>
                                        <input type="hidden" name="id" value="@article.Id" />
                                    </form>
                                }
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>