MB.Presentation.RazorPage/Areas/Administrator/Pages/CommentManagement/CommentList.cshtml.cs
using System.Collections.Generic;
using MB.Application.Contracts.Comment;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MB.Presentation.RazorPage.Areas.Administrator.Pages.CommentManagement
{
    public class CommentListModel : PageModel
    {
        private readonly ICommentApplication _commentApplication;
        public List<ViewCommentModel> Comments { get; set; }

        public CommentListModel(ICommentApplication commentApplication)
        {
            _commentApplication = commentApplication;
        }

        public void OnGet()
        {
            Comments = _commentApplication.GetComments();
        }

        public IActionResult OnPostConfirm(long id)
        {
            _commentApplication.Confirm(id);
            return RedirectToPage("./CommentList");
        }

        public IActionResult OnPostCancel(long id)
        {
            _commentApplication.Cancel(id);
            return RedirectToPage("./CommentList");
        }
    }
}

MB.Presentation.RazorPage/Areas/Administrator/Pages/CommentManagement/CommentList.cshtml
@page
@using MB.Domain.CommentAgg
@using Microsoft.AspNetCore.Mvc.TagHelpers
@model MB.Presentation.RazorPage.Areas.Administrator.Pages.CommentManagement.CommentListModel
@{
}

<div class="card">
    <div class="card-header">
        <h3 class="float-left">Comments List</h3>
    </div>
    <div class="card-body">
        <table class="table">
            <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Email</th>
                <th>Message</th>
                <th>Article</th>
                <th>Status</th>
                <th>CreationDate</th>
                <th>Operations</th>
            </tr>
            </thead>
            <tbody>
            @foreach (var comment in Model.Comments)
            {
                <tr>
                    <td>@comment.Id</td>
                    <td>@comment.Name</td>
                    <td>@comment.Email</td>
                    <td>@comment.Message</td>
                    <td>@comment.Article</td>
                    <td>
                        @if (comment.Status == Statuses.New)
                        {
                            <i class="fa fa-eye fa-2x text-info"></i>
                        }
                        @if (comment.Status == Statuses.Canceled)
                        {
                            <i class="fa fa-close fa-2x text-danger"></i>
                        }
                        @if (comment.Status == Statuses.Confirmed)
                        {
                            <i class="fa fa-check fa-2x text-success"></i>
                        }
                    </td>
                    <td>@comment.CreationDate</td>
                    <td>
                        @if (comment.Status == Statuses.New)
                        {
                            <form method="post" asp-page-handler="Confirm" class="float-left">
                                <button class="btn btn-success">Confirm</button>
                                <input type="hidden" name="id" value="@comment.Id"/>
                            </form>
                            <form method="post" asp-page-handler="Cancel" class="float-left">
                                <button class="btn btn-danger">Cancel</button>
                                <input type="hidden" name="id" value="@comment.Id"/>
                            </form>
                        }
                    </td>
                </tr>
            }
            </tbody>
        </table>
    </div>
</div>